sudo: required
dist: trusty
language: java
jdk:
- openjdk11
env:
  global:
  - MAVEN_OPTS="-Xmx10244M -Xss128M -XX:MetaspaceSize=512M -XX:MaxMetaspaceSize=1024M
    -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC"
cache:
  directories:
  - "$HOME/.m2/repository"
install: "/bin/true"
before_script:
- export MAVEN_SKIP_RC=true
- sudo chmod -R 777 "$HOME/.m2/repository";
- sudo chown -R travis:travis "$HOME/.m2/repository";
script:
- mvn install -DskipTests
deploy:
  provider: releases
  api_key:
    secure: SDq61rQSEiGphEqPbykUnxaVcvq9Qy6ub0D89vN8D5m645Uf/JQ/Vg9CcWVVT8CsfmHgYg36ImQorpkoA/alpbHCd1DJtTqaK65ySPm9th16M5ChJ2ewx2Wqr3Csa37wG42cxMvXGHLKitIZy7tHBscMZH5NkcKRybjvZzoO5ngdisyYXtbVtELYz1H0bF9cv+LcT67DOD90/l/E7kh/SJIgK+kZlLPlWXsR4vAkbXgtPnRjjtETlAqD61TNxktWQPr+pF+sAlLy5dBxPbsw/CGGpT73nqjy6iiJXMuCC3FeGL01BTL91uAeNNYnTz2eibMTbCFJIGqjapZME2xTtXUGrk6K4tZ930QAuy5jKUdRr52HbTZEJi/Iqr1gm2v9WPzF+iexFJH1pWqNdNKWxbjRhGE3nsBOX2mVj/9sms/YHE/k+7DuJluv627nYK6UHW+l1KH0lpevcyLKBIoT5mjjaATrqeQG9PlaixR6u/cGfNQfAGDYqHsZJodrLRdKhImq+PCvRrD+WZP56bpYULxJ5epDcCMBWGt9EdQtqGZczCe2YmoH6+hVaZ1PasUxU7ebA6kdUTrKuSUyaFCpvnBKls4JIi6U86jsWA0V2ixjCzvzzmtzi52cJVNGgz7x/hY10g0mfKBUYY7cvV41m3GuroiJnRLiLHm3yiD5wE8=
  file_glob: true
  file: "/home/travis/build/ahdis/org.hl7.fhir.core/org.hl7.fhir.validation.cli/target/*.jar"
  skip_cleanup: true
   on:
    repo: ahdis/org.hl7.fhir.core
    branch: develop
    tags: true
    draft: true
notifications:
  webhooks:
  - https://chat.fhir.org/api/v1/external/travis?api_key=2cBDy6BWgx4UaJKr6Wmp5IfQxrQJk97I&type=private&topic=java%20core&to=oliver.egger@ahdis.ch
